## Flask App
FROM python:3.8-slim-buster

WORKDIR /llm

COPY llm/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY /llm .
EXPOSE 5000
CMD [ "gunicorn", "-b", "0.0.0.0:5000", "--timeout", "60", "app:app" ]